### ISSUE TITLE
Wont compile on OS X 10.8

### ISSUE THREAD

**Issue by fbradyirl** [lhunath/UbiquityStoreManager#13]
Getting a number of compiler errors when trying to compile on an OS X 10.8 target.

E.g. Use of undeclared identifier 'NSPersistentStoreUbiquitousContainerIdentifierKey' 
- this is a 10.9 only property.

**Comment by lhunath** [comment]
You'll definitely need to compile with 10.9 as your target SDK.
